import Land from "../images/Land.png";
import Land2 from "../images/Land2.png";
import Land3 from "../images/Land3.png";
import Land4 from "../images/Land4.png";
import Land5 from "../images/Land5.png";
import Land6 from "../images/Land6.png";
import Land7 from "../images/Land7.png";
import Land8 from "../images/Land8.png";

export const GalleryValueData = [
    {images: "https://drive.google.com/uc?export=view&id=10UeBDJ5oSxT7_MUf2pYPnPvGRAOlK4r_"},
    {images: "https://drive.google.com/uc?export=view&id=1EQTJK0xg_d-wr8jO7HH-wECzF_JzKXDu"},
    {images: "https://drive.google.com/uc?export=view&id=1gnr7PqmYp1L8G7zCuzXXFxpRDjNM65XD"},
    {images: "https://drive.google.com/uc?export=view&id=1yijniatdMDxRIk9Xiq9VphhwmoyIHWyt"},
    {images: "https://drive.google.com/uc?export=view&id=1kFMHzbmh3m96BIki6v8jFJsa91nvjXap"},
    {images: "https://drive.google.com/uc?export=view&id=1Q3gCE5Z4JhPm1xkNqUJe2e8XRkJMt11-"},
    {images: "https://drive.google.com/uc?export=view&id=10ICiqpewFf6Kd3LPpXsnW6eSvrnH4K5B"},
    {images: "https://drive.google.com/uc?export=view&id=1MJMXHlbut_rJDiWRKcoPJEJIJB8f1asy"},
    {images: "https://drive.google.com/uc?export=view&id=16QFw0qPDSxS6_aZ5KeIwIdC-1RmpekzZ"},
    {images: "https://drive.google.com/uc?export=view&id=1YOguKy0Sk-Je0PnPz43t-vfM6t4loDVM"},
    {images: "https://drive.google.com/uc?export=view&id=1SrV-C189R41HJX-Z7PqN7mDf5NMYjcDa"},
    {images: "https://drive.google.com/uc?export=view&id=1idHy0FyBB5GNo825VwJz9Jlq83hwWuLj"},
    {images: "https://drive.google.com/uc?export=view&id=1C00w-bWVs9-6a2jb-c41W5on_vYigZAA"},
    {images: "https://drive.google.com/uc?export=view&id=1mCRmojcHec9o2kvd-pI4aR_Cri0_Fzot"},
    {images: "https://drive.google.com/uc?export=view&id=1UFIlvypFxDQ3Rz6hnUZu7s86QkxnNWi0"},
    {images: "https://drive.google.com/uc?export=view&id=1prz9NPK8kFOICR8WpGrqW0xKaWHtNOx8"},
    {images: "https://drive.google.com/uc?export=view&id=1IwtLBwBgEo21bqrIvcAERVXKloIwav-k"},
    {images: "https://drive.google.com/uc?export=view&id=1PjmmksgS4b2Pn7ysyKwjHDvRcKunBVQm"},
    {images: "https://drive.google.com/uc?export=view&id=1SMafxFCTbtWQAr2GUlTE9bvJbaxfM6KZ"},
    {images: "https://drive.google.com/uc?export=view&id=1o3j85fEzObOC_wqqzX1cmirIOUiAU6SM"},
    {images: "https://drive.google.com/uc?export=view&id=1XapeJ83hzae1wDKy9B6weOCVivzOARdD"},
    {images: "https://drive.google.com/uc?export=view&id=1dIoxrwacy3YWJboSb663pjk2KF3yTdGa"},
    {images: "https://drive.google.com/uc?export=view&id=1-XTeH6MamlxdmxvUsU8kBfcm8aMyJGTw"},
    {images: "https://drive.google.com/uc?export=view&id=1THxqY7gQMcobKcf63pgVCfkN2oKY49rH"},
    {images: "https://drive.google.com/uc?export=view&id=1Y0r-lWITijsr7FveFOzS6PFOAWDbPS8y"},
    {images: "https://drive.google.com/uc?export=view&id=1Je3-HXiKVLIwP3vVWd-So4jhZDn6u8qP"},
    {images: "https://drive.google.com/uc?export=view&id=1YtanZEV7vAJilwaqLI9Z04YWwYdMk736"},
    {images: "https://drive.google.com/uc?export=view&id=1xyHR__jTmM_NbMzHCuHRMFXj1cGnYwAk"},
    {images: "https://drive.google.com/uc?export=view&id=1cAgrs2QU0y5krXJFXBAsThx0Mi2-pbmq"},
    {images: "https://drive.google.com/uc?export=view&id=1LirnUbDo_MwFoaPNh5a6tJHKIHcDs9Iy"},
    {images: "https://drive.google.com/uc?export=view&id=1inOXk8Vfzxfs_aNYD7hz7hUi8JTtsq_J"},
    {images: "https://drive.google.com/uc?export=view&id=1AQFRsLLCfxrqvL1VuSlJI4mYWuhuBOUr"},
    {images: "https://drive.google.com/uc?export=view&id=1vUs-69MVGlKaONyn3fqYJCbeFOiSrxs9"},
    {images: "https://drive.google.com/uc?export=view&id=1qq6wQz49en77o_Z9nFnxgBD5JguTlIq6"},
    {images: "https://drive.google.com/uc?export=view&id=1rDCYnj0FLWq-no6HN2bLm9G6o8RaeLk8"},
    {images: "https://drive.google.com/uc?export=view&id=1pDFe_pu2Q7mlzze1uJVKYNjJmRL0DJ8_"},
    {images: "https://drive.google.com/uc?export=view&id=1mLawkFWbzShWzZLjm3U4YXPTbQ5tf6if"},
    {images: "https://drive.google.com/uc?export=view&id=1eZWs7sUqA3mu8y-1bkwaU9pPG-ZQRYIn"},
    {images: "https://drive.google.com/uc?export=view&id=1T580zM5HleaBIfijsM2-xYDoDNoJbbB_"},
    {images: "https://drive.google.com/uc?export=view&id=1Ia1tiVZ9NX1HxduQkiDWYRXUJPkbgDwY"},
    {images: "https://drive.google.com/uc?export=view&id=1iSWU8c1TGMuNkRbkeDm5sUdfnmXsiARd"},
    {images: "https://drive.google.com/uc?export=view&id=1LeMczzyIMY98YFdDfGJGxQLtSQRItp7C"},
    {images: "https://drive.google.com/uc?export=view&id=14-Q_QL3uDWrNVnmNZM-O9NNF-2acJmGW"},
    {images: "https://drive.google.com/uc?export=view&id=1BQmPPA7IzY1pud8DiSVJKMlnLOkqISI-"},
    {images: "https://drive.google.com/uc?export=view&id=180Kt34ZOUcMMYhEgGkTlPAJtV7RzsuSA"},
    {images: "https://drive.google.com/uc?export=view&id=15MjU1ooP-fDxQa0CpVZQPr5a7fJ-ucTG"},
    {images: "https://drive.google.com/uc?export=view&id=1fqWOKpGg213G5wUP8nOmo88MKwX_ro05"},
    {images: "https://drive.google.com/uc?export=view&id=1p2kvnw5oIMf9-uTXo5Tqt8daaXfvlywt"},
    {images: "https://drive.google.com/uc?export=view&id=1svRb8CKR4xeR-ldySmRfm5TRO-sXjjGK"},
    {images: "https://drive.google.com/uc?export=view&id=1wf10aOmYBMwkLx06X-4lq80rfm2dMR0i"},
    {images: "https://drive.google.com/uc?export=view&id=1o6zFabCQtcYLcqY4EDeswnKUDA16_aH1"},
    {images: "https://drive.google.com/uc?export=view&id=1HJaK9uvYzDM-rBCow9yu1ID-zskOAscn"},
    {images: "https://drive.google.com/uc?export=view&id=13ULrLK71geD-AjNI6lMEjpdsY3xXK_-D"},
    {images: "https://drive.google.com/uc?export=view&id=1HR1J9rHjpQA53M3PvOSFDUnxttuMmhv8"},
    {images: "https://drive.google.com/uc?export=view&id=16cEHXvBES3UebtUk05gyzNaWeSas_bHA"},
    {images: "https://drive.google.com/uc?export=view&id=1HI0Yj8bOPIKpfIjNN2d485XhM6m5xn_d"},
    {images: "https://drive.google.com/uc?export=view&id=1HrpBx44F9wPu9P2Y2iEZ5oWZd9bYrH8H"},
    {images: "https://drive.google.com/uc?export=view&id=1pxnndIbEmTI9O-TYxEyPBe5Zmi-bjC8-"},
    {images: "https://drive.google.com/uc?export=view&id=1X10KtesbcJ-cbojPEMPAHnRsstZTLtFo"},
    {images: "https://drive.google.com/uc?export=view&id=1AxvLRhaijTM4kiVaEyMRDhAKQFoPJo3U"},
    {images: "https://drive.google.com/uc?export=view&id=1H0skCUNocSt2pvToyT2SZXcQglWpQokB"},
    {images: "https://drive.google.com/uc?export=view&id=1errC92-XxvKof245qXTJBdDJNfLg73mT"},
    {images: "https://drive.google.com/uc?export=view&id=1m0o-WFuXvU5RVbnpCjio3TwkLJ6-wsgD"},
    {images: "https://drive.google.com/uc?export=view&id=12RUKANzW6mIjouO4OzSj9gd6-WATjENY"},
    {images: "https://drive.google.com/uc?export=view&id=1ba1S2LpuzSilzXGtU2q80Ezzz7XhFwWs"},
    {images: "https://drive.google.com/uc?export=view&id=1YEUv54fjcUjOWot0XmrgtXkS6CWSxeFO"},
    {images: "https://drive.google.com/uc?export=view&id=1XwbMqyYoj7Z5XNohq1DWQHutGRvEc6Fe"},
    {images: "https://drive.google.com/uc?export=view&id=1VcptWFgNYMyrQMxAi7UNS5u1qYouKPu_"},
    {images: "https://drive.google.com/uc?export=view&id=1jCOIFb6P0TXDIe2m79K41vvQpb1c6YX_"},
    {images: "https://drive.google.com/uc?export=view&id=1dXOBq0tloHzYZIovpqItnhSS0LZ3k_zh"},
    {images: "https://drive.google.com/uc?export=view&id=1_uvbIquR8RHXUj72NmwepQbaAtukB9iJ"},
    {images: "https://drive.google.com/uc?export=view&id=1TXxLlHQVn4eIzpeK_8EXt49NybDcvihg"},
    {images: "https://drive.google.com/uc?export=view&id=1C-JEug75eHUEElRtBORWIaKVSabC_REL"},
    {images: "https://drive.google.com/uc?export=view&id=1d3OFbjLPOUMrgQlD3s4Wn5sbslUKYfq1"},
    {images: Land,},
    {images: Land2,},
    {images: Land3,},
    {images: Land4,},
    {images: Land5,},
    {images: Land6,},
    {images: Land7,},
    {images: Land8,},
];